### ISSUE TITLE
Not working via the server

### ISSUE THREAD

**Issue by ohm1998** [newnewcoder/flask-hls-demo#2]
Hey, Great work,
I was trying to deploy this on the server and testing it using http://stream-tester.jwplayer.com/ but it didn't work.

Could you help me out?
I am having a similar use case but with more recursive directories.

I have deployed your code on the server and the HTML works , but the playlist.m3u8 on the testing doesn't work. I don't understand what is the issue
Happened with my files too.

**Comment by newnewcoder** [comment]
If `index.html` work, try turning on browser develop mode to view `network` tab, you may find something useful information!?

**Comment by ohm1998** [comment]
Hey checked it, Was CORS issue from server side , works using flask-cors (incase you are developing API for video streaming ).
Thank you!
